package cg;

public enum Replacement {
	PACKAGE_NAME, CLASS_NAME, INSTANCE_NAME, SEPERATOR, GENERIC_TYPE_NAME, GENERIC_TYPE_KEY, GENERIC_TYPE_VAL,

	ABSTRACT_CLASS_NAME, ABSTRACT_INSTANCE_NAME, TMP_CLASS_NAME, TMP_INSTANCE_NAME, TMP_INSTANCE_VALUE, ITEM_NAME,
	TARGET_CLASS_NAME, TARGET_INSTANCE_NAME, INIT_CLASS_WITH_DEFAULT_VALUE, DEFAULT_VALUE,

	ASSIGN_SYMBOL, NEW_LINE, END_OF_LINE, CLASS_END_LINE, FIELD_CLASS_NAME, FIELD_INSTANCE_NAME, FIELD_VALUE, QUALIFIER,
	METHOD_NAME, METHOD_RETURN_TYPE, METHOD_PARAMS, METHOD_PARAMS_VARIABLE, MATCH_PARAMS_VARIABLE,

	PRIVILEDGE_MODIFIER, STATIC_MODIFIER, ABSTRACT_MODIFIER, FINAL_MODIFIER, VOLATILE_MODIFIER, SYNC_MODIFIER, METHOD_PARAMS_DECLARE,
	METHOD_BODY, METHOD_RETURN_VALUE,

	LAMBDA_PARAMS_VARIABLE,

	THROWS_EXCEPTION, TRY_BODY, EXCEPTIONS_DECLARE, EXCEPTION_NAME, EXCEPTION_INSTANCE_NAME, CATCH_BODY, FINALLY_BODY,

	ANY_MATCH, RETURN_TYPE, RETURN_TYPE_INSTANCE,

	ASSERT_NOT_NULL, EXPECT_VALUE, ACTUAL_VALUE,

	EXCEPTION_CLASS, PREFIX_STR, IF_EXPRESSION, ELSE_BLOCK, IF_BODY, ELSE_BODY,

	BLOCK_BODY,

	CORE_POOL_SIZE, MAX_POOL_SIZE, NEW_THREAD_FACTORY,

	PATH, METHOD_STR, HEADERS, CONSUMERS, PRODUCES, RESPONSE_BODY,
	
	TAG_NAME,ID,LINK,TARGET, REQUEST_METHOD, 
	
	GROUP_ID, ARTIFACTOR_ID, VERSION, SCOPE,
}
